# Generated by Django 3.1.5 on 2021-01-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='img',
            field=models.ImageField(default='static\\food\\images\\Not_found.jpg', upload_to='static\\food\\images'),
        ),
    ]
